spring.application.name=Flash_Sales
spring.config.import=optional:file:.env[.properties]
# 1. Credenciales de la Base de Datos (Inyectadas desde tu configuración de IntelliJ)
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:flash_sales_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# 2. Comportamiento de Hibernate (El ORM)
# 'update' le dice a Hibernate que cree las tablas si no existen, o las actualice si añades columnas
spring.jpa.hibernate.ddl-auto=create-drop

# 3. Auditoría visual (Opcional pero muy recomendado para aprender)
# Esto imprimirá en la consola los "CREATE TABLE" y "SELECT" que Hibernate genere
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# 1. Point Spring to the exact URL of your Keycloak Realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm

# 2. Tell Spring which Client ID to expect
spring.security.oauth2.resourceserver.jwt.audiences=myclient

# 3. (Optional but recommended) Set a port for Spring Boot so it doesn't conflict with Keycloak
server.port=8081

