spring.application.name=Flash_Sales
spring.config.import=optional:file:.env[.properties]
# 1. Credenciales de la Base de Datos (Inyectadas desde tu configuración de IntelliJ)
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:flash_sales_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# 2. Comportamiento de Hibernate (El ORM)
# 'update' le dice a Hibernate que cree las tablas si no existen, o las actualice si añades columnas
spring.jpa.hibernate.ddl-auto=update

# 3. Auditoría visual (Opcional pero muy recomendado para aprender)
# Esto imprimirá en la consola los "CREATE TABLE" y "SELECT" que Hibernate genere
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true